- alias: 'T채nd halllampa n채r solen g책r ner'
  trigger:
    - platform: sun
      event: sunset
  action:
    service: light.turn_on
    entity_id: switch.hallen

- alias: 'Sl채ck halllampa vid 22:30'
  trigger:
    - platform: time
      at: "22:30:00"
  action:
    service: switch.turn_off
    entity_id: switch.hallen


