- alias: 'Tänd takfotsbelysning vid solnedgång'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:45:00"
  action:
    service: switch.turn_on
    entity_id: switch.takfotsbelysning

- alias: 'Släck tackfotsbelysning efter klockan 23'
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.takfotsbelysning
